src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/** @ORM\Entity */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="string") */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="Product", mappedBy="category")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    public function __toString()
    {
        return (string) $this->getName();
    }

    /**
     * @return mixed
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * @param mixed $products
     */
    public function setProducts($products)
    {
        $this->products = $products;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/** @ORM\Entity */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="text") */
    private $name;

    /** @ORM\Column(type="decimal", precision=19, scale=4) */
    private $price; // NOTE: chosen for simplicity purpose

    /** @ORM\Column(type="integer") */
    private $vatPercent;

    /**
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="products")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    public function __toString()
    {
        return sprintf('(%s, %s VAT %s)',
            $this->getName(),
            $this->getDisplayPrice(),
            $this->getVatPercent()
        );
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function getCategory()
    {
        return $this->category;
    }

    public function setCategory(Category $category)
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getVatPercent()
    {
        return $this->vatPercent;
    }

    /**
     * @param mixed $vatPercent
     */
    public function setVatPercent($vatPercent)
    {
        $this->vatPercent = $vatPercent;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param mixed $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    public function getDisplayPrice()
    {
        return money_format('%.2n', $this->price);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Model\CartModel;
use App\Model\ProductModel;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CartController extends Controller
{
    /**
     * @Route("/cart/add/{id}", name="cart_add")
     * @throws NotFoundHttpException
     */
    public function addAction(string $id)
    {
        $cartModel = $this->get(CartModel::class);
        $productsModel = $this->get(ProductModel::class);

        $product = $productsModel->getById($id);

        if (empty($product)) {
            throw new NotFoundHttpException('Product not found.');
        }

        $cartModel->addProduct($product);

        return $this->redirectToRoute('cart_view');
    }

    /**
     * @Route("/cart/remove/{id}", name="cart_remove", methods={"POST"})
     */
    public function removeAction(string $id)
    {
        $cartModel = $this->get(CartModel::class);

        $productsModel = $this->get(ProductModel::class);
        $product = $productsModel->getById($id);

        $cartModel->removeProduct($product);

        return $this->redirectToRoute('cart_view');
    }

    /**
     * @Route("/cart", name="cart_view")
     */
    public function viewAction()
    {
        $cartModel = $this->get(CartModel::class);

        return $this->render('Cart/view.html.twig', [
            'cart' => $cartModel
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Model\CategoryModel;
use App\Model\ProductModel;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ProductController extends Controller
{
    /**
     * @Route("/", name="home")
     */
    public function indexAction()
    {
        $productsModel = $this->get(ProductModel::class);
        $products = $productsModel->getAllProducts();

        $categoryModel = $this->get(CategoryModel::class);
        $categories = $categoryModel->getAllCategories();

        return $this->render('Product/index.html.twig', [
            'products' => $products,
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/category/{id}")
     * @throws NotFoundHttpException
     */
    public function categoryAction(string $id)
    {
        $productsModel = $this->get(ProductModel::class);
        $products = $productsModel->getProductsByCategoryId($id);

        $categoryModel = $this->get(CategoryModel::class);
        $category = $categoryModel->getById($id);

        if (empty($category)) {
            throw new NotFoundHttpException('Category not found #' . $id);
        }

        return $this->render('Product/category.html.twig', [
            'products' => $products,
            'category' => $category
        ]);
    }
}

templates/Cart/view.html.twig
{% extends "Layout/base.html.twig" %}

{% block content %}
    {% for vatPercent, productsByVat in cart.getProductsInVatBuckets %}
        <h5>VAT: {{ vatPercent }}</h5>
        {% for cartProduct in productsByVat %}
            <li>
                {{ cartProduct.product.name }} {{ cartProduct.count }} * {{ cartProduct.product.displayPrice }} =
                {{ cartProduct.count * cartProduct.product.Price }}

                <a href="{{ path('cart_add', {id: cartProduct.product.id}) }}">[+1]</a>

                <form method="post" action="{{ path('cart_remove', {id: cartProduct.product.id}) }}">
                    <input type="submit" value="[X]" />
                </form>
            </li>
        {% endfor %}
    {% else %}
        <p>No products found.</p>
    {% endfor %}

    Total: {{ cart.total }}
{% endblock %}

templates/Layout/base.html.twig
<p>
    <b>To the <a href="{{ path('home') }}">Home</a></b>
</p>

<p>
    <b>To the <a href="{{ path('cart_view') }}">Cart</a></b>
</p>
<p>
    {% if categories is defined %}
        {% for category in categories %}
            <a href="{{ path('app_product_category', {id: category.id}) }}">{{ category.name }}</a>
        {% else %}
            <p>No categories found.</p>
        {% endfor %}
    {% endif %}
    <hr size="1" />
</p>
{% block content %}
{% endblock %}

templates/Product/category.html.twig
{% extends "Layout/base.html.twig" %}

{% block content %}
    <h1>Category {{ category.name }}</h1>
    {% for product in products %}
        <li>{{ product.category.name }} - {{ product.name }} - {{ product.getDisplayPrice }} <a href="{{ path('cart_add', {id: product.id}) }}">[Add]</a></li>
    {% else %}
        <p>No products found.</p>
    {% endfor %}
{% endblock %}

templates/Product/index.html.twig
{% extends "Layout/base.html.twig" %}

{% block content %}
    <h1>All products</h1>
    {% for product in products %}
        <li>{{ product.category.name }} - {{ product.name }} - {{ product.getDisplayPrice }} <a href="{{ path('cart_add', {id: product.id}) }}">[Add]</a></li>
    {% else %}
        <p>No products found.</p>
    {% endfor %}

{% endblock %}